# Generated by Django 5.0.6 on 2025-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_semester_note_subject_note_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
